Sprint 07
easywinteam/quiz-ios-1 pull request #6
Opened 2023-03-15 17:13 UTC by easywinteam

Домашнее задание №7. Проведен рефакторинг проекта "КиноКвиз", проект переведен с паттерна MVC на MVP. Создан презентер, часть проекта покрыта unit и UI тестами

2023-03-16 17:49 UTC, protos17 requested changes

2023-03-16 17:49 UTC, protos17 commented on MovieQuiz/Services/MoviesLoader.swift
> +    //k_azezgvdf
Рекомендую удалить лишние комментарии

2023-03-16 17:49 UTC, protos17 commented on MovieQuizTests/ArrayTests.swift
> +        let array = [1, 1, 2, 3, 5]
Рекомендую использовать уникальные значения, потому что array[safe: 0] и array[safe: 1] дадут одинаковый результат

2023-03-16 17:49 UTC, protos17 commented on MovieQuizTests/ArrayTests.swift
> +        let array = [1, 1, 2, 3, 5]
Рекомендую использовать уникальные значения

2023-03-16 17:49 UTC, protos17 commented on MovieQuizTests/MoviesLoaderTests.swift
> +class MoviesLoaderTests: XCTestCase{
Для тестовых классов рекомендую тоже проставлять final

2023-03-16 17:49 UTC, protos17 commented on MovieQuizTests/MoviesLoaderTests.swift
> +                //Сравниваем данные с тем, с чем мы предполагали
Здесь мы сравниваем ни с success, a c failure

2023-03-16 17:49 UTC, protos17 commented on MovieQuizUITests/MovieQuizUITests.swift
> +        app.buttons["No"].tap()
Тест называется testYesButton(), а ты здесь тестируешь кнопку "No"

2023-03-16 17:49 UTC, protos17 commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(3)
Нет необходимости задерживать начало теста на 3 секунды, рекомендую удалить

2023-03-17 08:50 UTC, easywinteam commented on MovieQuizUITests/MovieQuizUITests.swift
> +        app.buttons["No"].tap()
Исправил

2023-03-17 08:52 UTC, easywinteam commented on MovieQuizTests/MoviesLoaderTests.swift
> +class MoviesLoaderTests: XCTestCase{
Сделано

2023-03-17 08:54 UTC, easywinteam commented on MovieQuizTests/ArrayTests.swift
> +        let array = [1, 1, 2, 3, 5]
Теперь для теста используются уникальные целочисленные значения

2023-03-17 08:54 UTC, easywinteam commented on MovieQuizTests/ArrayTests.swift
> +        let array = [1, 1, 2, 3, 5]
Исправлено

2023-03-17 08:56 UTC, easywinteam commented on MovieQuiz/Services/MoviesLoader.swift
> +    //k_azezgvdf
Ненужные отладочные комментарии удалены

2023-03-18 09:17 UTC, protos17 approved these changes

2023-03-18 09:17 UTC, protos17 commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(3)
Нет необходимости ставить задержку, рекомендую убрать

2023-03-18 09:17 UTC, protos17 commented on MovieQuizUITests/MovieQuizUITests.swift
> +        sleep(2)
Рекомендую убрать

2023-03-18 09:23 UTC, merged